name = "mydnsproxy-dev0"
main = "src/index.ts"
account_id = "9a3d95f55feeaa895f035cbd07a3de41"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
routes = [
    { pattern = "adblock.staging.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "family.staging.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "freedom.staging.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "paranoia.staging.mydns.network/*", zone_name = "mydns.network" }
]

# Observability
[observability]
enabled = true

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "mydnsproxy-dev"

[env.prod]
name = "mydnsproxy-prod"
routes = [
    { pattern = "adblock.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "family.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "freedom.mydns.network/*", zone_name = "mydns.network" },
    { pattern = "paranoia.mydns.network/*", zone_name = "mydns.network" }
]

    [[env.prod.analytics_engine_datasets]]
    binding = "ANALYTICS"
    dataset = "mydnsproxy-prod"
